name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - run: touch meritz/.env
      - run: echo "${{ secrets.ENV_FILE }}" > meritz/.env
      - run: cat meritz/.env


      - name: Docker build & push to dev
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meritz-web .
          docker push ${{ secrets.DOCKER_USERNAME }}/meritz-web

      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        with:
          host: ${{ secrets.HOST_DEV }} # GCP 퍼블릭 IPv4 DNS
          username: ${{ secrets.USERNAME }} # GCP NAME
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker stop $(docker ps --filter name=meritz-web -a -q)
            docker rm -f $(docker ps --filter name=meritz-web -a -q)
            docker pull ${{ secrets.DOCKER_USERNAME }}/meritz-web
            docker run -d -p 4000:3000 --name mertiz-web ${{ secrets.DOCKER_USERNAME }}/meritz-web 
            docker image prune -f
